# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

if Rails.env.production?
  task :yarn_install do
    system "yarn install"
    Rake::Task["assets:clobber"].invoke
  end

  Rake::Task["assets:precompile"].enhance ["yarn_install"]
end
